<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/CSS/styles.css">
</head>
<body>
<a href="/">HOME</a>
<a href="/complete"><h2>Completed Tasks</h2></a>

<h1>To Do List</h1>
<br>
<h2>Current task to edit: <br><?= $singleToDoArray['to_do_message']?></h2>
<h2>Change to: </h2>
<form method="post" action="/edit/<?= $singleToDoArray['id'] ?>'">
    <div class="newToDoDiv">
    <input type="text" name="<?= $singleToDoArray['id'] ?>" value="<?= $singleToDoArray['to_do_message']?>">
    <label for="editDate">Edit date</label>
    <input type="date" name="editDate" id="editDate" class="textInputBox" value="<?= $singleToDoArray['deadline'] ?>">
    <input type="submit" value="edit"></form>
    </div>
<br>
<br>

</body>
</html>
