<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/CSS/styles.css">
</head>
<body>
<h1>To Do List</h1>
<br>
<h2>Current task to edit: <br><?= $singleToDoArray['to_do_message']?></h2>
<h2>Change to: </h2>
<form method="post" action="/edit/<?= $singleToDoArray['id'] ?>'">
    <input type="text" name="<?= $singleToDoArray['id'] ?>">
    <label for="editDate">Edit date</label>
    <input type="date" name="editDate" id="editDate" class="textInputBox">
    <input type="submit" value="edit"></form>
<br>
<br>
<a href="/complete"><h2>Completed Tasks</h2></a>
<a href="/">HOME</a>
</body>
</html>
