<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/CSS/styles.css">
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js'></script>
    <script defer>
        let toDos = <?php echo json_encode($toDoArray); ?>;
        console.log(toDos)
        document.addEventListener('DOMContentLoaded', function() {
            let calendarEl = document.getElementById('calendar');
            let calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                events: toDos.map(toDo => { return {
                    title: toDo.to_do_message,
                        start: toDo.deadline
                }})
            });
            calendar.render();
        });

    </script>
</head>
<body>
<h1>To Do List</h1>
<h2>Add to do:</h2>
<div>
<form method="post" action="/add">
    <p><label for="newToDo">New to do: </label></p>
    <div class="newToDoDiv">
        <input class="textInputBox" type="text" id="newToDo" name="newToDo" placeholder="What do you need to do?" required>
        <label for="newToDoDate">Due by: </label>
        <input class="textInputBox" type="date" id="newToDoDate" name="newToDoDate" required>
        <input class="textInputBox" type="submit" value="Add to do">
    </div>
</form>
</div>
<br>
<h2>Do these things: </h2>
<div class="toDoBoard">
<?PHP
foreach ($toDoArray as $toDo)
{
    echo '<div class="eachToDoDiv">';
    echo '<h4>' . $toDo['to_do_message'] . '</h4>';
    echo '<div><form method="post" action="/done"><input type="submit" name="'.$toDo['id'].'" value="✓"></form>';
    echo '<form method="get" action="/edit/'.$toDo['id'].'"><input type="submit" name="'.$toDo['id'].'" value="✎"></form></div>';
    echo '</div>';
}
?>
</div>
<br>
<br>
<a href="/complete"><h2>Completed Tasks</h2></a>
<div class="calendar_flex">
    <div class="calendar">
        <div id='calendar'></div>
    </div>
</div>


</body>
</html>
