<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/CSS/styles.css">
</head>
<body>
<h1>To Do List</h1>
<h2>Add to do:</h2>
<div>
<form method="post" action="/add">
    <p><label for="newToDo">New to do: </label></p>
    <input type="text" id="newToDo" name="newToDo" placeholder="What do you need to do?">
    <input type="submit" value="Add to do">
</form>
</div>
<br>
<h2>Do these things: </h2>
<?PHP
foreach ($toDoArray as $toDo)
{
    echo '<h4>' . $toDo['to_do_message'] . '</h4>';
    echo '<div style="display: flex; justify-content: center; gap: 3px;"><form method="post" action="/done"><input type="submit" name="'.$toDo['id'].'" value="✓"></form>';
    echo '<form method="get" action="/edit/'.$toDo['id'].'"><input type="submit" name="'.$toDo['id'].'" value="✎"></form></div>';

}
?>
<br>
<br>
<a href="/complete"><h2>Completed Tasks</h2></a>
</body>
</html>
